theme: jekyll-theme-minimal
social:
  blog: http://blog.myso.kr/
  post: http://post.naver.com/cw4196
  tv: http://tv.naver.com/360trip
  facebook: https://www.facebook.com/cw4196
  twitter: https://twitter.com/cw4196
  github: https://github.com/myso-kr
  tumblr: https://www.tumblr.com/blog/cw4196
  youtube: https://www.youtube.com/channel/UCr7tBzFRyLLRmrIdEFMLkkA
